name: CX-V2 Amplify Deploy
"on":
  push:
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Flutter Web Build/Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: | 
          cd cx_frontend
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release
      - name: Copy into deployment folder
        shell: pwsh
        run: | 
          .\buildweb.ps1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit build artifacts
